### ISSUE TITLE
Causes add comment to use java comment instead of xml comment tag

### ISSUE THREAD

**Issue by SavvySkylark** [camel-tooling/camel-lsp-client-vscode#88] opened 2019-02-08 03:06 UTC
When enabling this plugin the add comment function in vscode adds // instead of an xml comment tag to xml files.

**Comment by apupier** [comment] 2019-02-08 08:33
@SavvySkylark thanks for your report.

I'm unable to reproduce.
 I tried:
- Ctrl+ /
- use command Palette "Add Line comment"
- use command Palette "Toggle block comment" after selecting some characters in the xml file

Which method are you using to add comment? is it happening also in the ways I mentioned above?
Can you provide one of the xml file for which it occurs?
Can you provide the list of extensions that are installed? (code --list-extensions)

**Comment by SavvySkylark** [comment] 2019-02-14 16:32
Will do. I'll try to follow up on this this weekend.

**Comment by apupier** [comment] 2019-03-21 13:25
@SavvySkylark I'm closing. Please reopen when you have time to provide more information.

**Closed by apupier** 2019-03-21 13:25 UTC
Labels: BUG

**Comment by uzijazi** [comment] 2019-11-15 10:40
Hello, I have the same issue as shown in the attached gif.
![WrongXMLComment](https://user-images.githubusercontent.com/47883535/68936691-612ebe00-079b-11ea-87c9-6659057f8c76.gif)

What i've done:
1. Open vscode with Language Support for Apache Camel disabled
2. Open a pom.xml file for editing
3. Try to comment out some lines as Block (even the same with one line) by pressing Ctrl + # for doing a default comment (even the same result by pressing Ctrl + K + U
4. Get the correct comment ""

5. Enabled the Language Support for Apache Camel
6. Open the pom.xml again
7. Try to comment out some lines
8. Get the wrong comment styple with double slashes "//"

vscode:
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Language Support for Apache Camle by Red Hat: 0.0.18


[pom.zip](https://github.com/camel-tooling/camel-lsp-client-vscode/files/3851074/pom.zip)

**Comment by apupier** [comment] 2019-11-15 10:52
thanks for providing more details.
it should be fixed in next release https://github.com/camel-tooling/camel-lsp-client-vscode/pull/173 https://issues.jboss.org/browse/FUSETOOLS2-47
Awaiting for the new release, you can install a vsix manually from a snapshot version from here https://download.jboss.org/jbosstools/vscode/snapshots/vscode-apache-camel/

**Comment by apupier** [comment] 2019-11-15 10:53
I think I wasn't reproducing at initial reported time because I think it was depending on the load order of language configurations in VS Code.
