### ISSUE TITLE
Auto-completion doesn't work on MacOS

### ISSUE THREAD

**Issue by tkamata-redhat** [camel-tooling/camel-lsp-client-vscode#903] opened 2022-02-12 11:30 UTC
# Issue information

> Define issue title **short** and **most specific** to the problem.
Auto-completion doesn't work.

> Tag each new issue with relevant **LABELS** (*Bug*, *Improvement*, etc.).
*Bug*

### Environment

- Language Support for Apache Camel version: e.g. "**v0.0.13**" ?
  - **v0.1.4**
  - **v0.1.5**
- OS:
    - [ ] Linux (*RHEL*, *Fedora*, *Ubuntu*, ...)
    - [ ] Windows
    - [x] macOS

### Description of wrong behavior

- AUto-completion doesn't work. It just show "loading...".

### Exact steps to reproduce issue

1. Insert new line as like "\<to />" in camel-context.xml.
2. Auto-Complition doesn't show the attribute "uri" nor camel comonent in uri attribute.
3. Auto-Complition doesn't show the attribute "uri" nor candidates of camel comonents and options in uri attribute.

### Description

- ...

### Expected behaviour

- ...

### Screenshot (*optional*)

- ...

**Comment by apupier** [comment] 2022-02-14 08:35
Can you provide the camel-context.xml that you are using please?
Please make sure that the namespace is provided.

> Auto-Complition doesn't show the attribute "uri"

This part is handled by the VS Code xml extension, if the namespace and xsd are properly configured.

**Comment by tkamata-redhat** [comment] 2022-02-15 03:13
My camel-context.xml is below.

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
          http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans-2.0.xsd
          http://camel.apache.org/schema/spring https://camel.apache.org/schema/spring/camel-spring.xsd">
  <camelContext id="camelContext-0001" xmlns="http://camel.apache.org/schema/spring">
    <route id="sample-route">
      <from uri="timer:sample-timer?delay=1000&amp;period=1000"/>
      <process ref="sampleProcessor" />
      <split parallelProcessing="true">
        <simple>${body}</simple>
        <log message="${body}"/>
      </split>
      <log message="*****" />
    </route>
  </camelContext>
</beans>
```

v0.1.3 shows candidates of camel components immediately.
But, v0.1.4 and v0.1.5 doesn't work it. v0.1.4 and v0.1.5 shows only "Loading...".
<img width="962" alt="loading_attribute" src="https://user-images.githubusercontent.com/25147163/153985156-f8704762-2002-4269-b52b-ffd59caacbc8.png">
<img width="962" alt="loading_components" src="https://user-images.githubusercontent.com/25147163/153985230-a6f04ff0-7ef8-489c-abfd-baadb71100fe.png">


Some errors were showed VS Code extension in "Runtime Status" tab.
"Uncaught Errors" says "Header must provide a Content-Length property".
No Error was showed as v0.1.3.
<img width="1206" alt="runtimestatus" src="https://user-images.githubusercontent.com/25147163/153985300-175b1932-2a19-41f4-9c0e-149e271ec63e.png">

**Comment by apupier** [comment] 2022-02-15 09:04
it smells Camel Language Server or one of its dependencies is writing on console output.

It will interesting to have the communication details of the Language Server for Camel and VS Code client. Can you please use the setting `"LANGUAGE_ID_APACHE_CAMEL.trace.server": "verbose"` for reference https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server ?

**Comment by apupier** [comment] 2022-02-15 09:12
(I have not precised but of course I cannot reproduce, I'm on Fedora 35 with Java 11)

i'm also wondering if it cannot be due to other LSPs, such as the xml one as there is a problem with the completion on the uri tag.

Would worth adding also `"xml.trace.server": "verbose"`

and looking to [lemminx.log](https://github.com/redhat-developer/vscode-xml/blob/9a06fc5428cb7d5cec5bb5ccb67ddd92cd16937d/src/extension.ts#L56) file

**Comment by apupier** [comment] 2022-02-15 09:26
the traces will appear in View -> Output 6> XML Support and View -> Output -> Language Support for Apache Camel

**Comment by tkamata-redhat** [comment] 2022-02-15 10:29
This is  Camel Language Server's log file.
[camel_lsp.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8068204/camel_lsp.log)

There is no log file under ~/.lemminx. There is cache directory only.

**Comment by apupier** [comment] 2022-02-15 15:02
I see nothing that could explain the blocked "loading..." in the provided logs. There are responses to the completion requests.

**Comment by apupier** [comment] 2022-02-16 08:54
Some ideas to try to find a potential track:
* What is the version of VS Code?
* What is the version of Java? `java version` from command-line, `echo %JAVA_HOME%` from command-line, any java home specified in settings of vs code?
* Are you able to reproduce on a clean VS Code with a single extension installed? with both VS Code xml and vs code language support for Camel?

**Comment by tkamata-redhat** [comment] 2022-02-17 06:09
@apupier I get informations as below.

> What is teh version of Mac OS?

Monterey 12.2.1

> What is the version of VS Code?

January 2022 (version 1.64)

> What is the version of Java? java version from command-line

$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

> echo %JAVA_HOME% from command-line

$ echo %JAVA_HOME%
%JAVA_HOME%

> any java home specified in settings of vs code?

None

> Are you able to reproduce on a clean VS Code with a single extension installed? with both VS Code xml and vs code  language support for Camel?

I have tried it with Extension Pack for Apache Camel by Red Hat.
<img width="480" alt="extensions_list" src="https://user-images.githubusercontent.com/25147163/154413936-463cfea7-ae61-4abf-9ef7-d52e0bf73292.png">


> Do you have Camel URI completion working on java or yaml files?

The completion doesn't work on java too.

<img width="475" alt="completion_java" src="https://user-images.githubusercontent.com/25147163/154414095-92386122-1f96-48b9-baea-c80b9df4e634.png">

> it would be nice to find the "Header must provide a Content-length property" in some logs. Maybe there will be more information.
>  Maybe in Output - > View -> Log (Extension Host) or Log(main) or Log (Shared)
log files are blow.
[lsp_camel.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8085980/lsp_camel.log)
[xmlsupport.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8085978/xmlsupport.log)
[log_main.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8085981/log_main.log)
[log_shared.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8085982/log_shared.log)
[log_extension_host.log](https://github.com/camel-tooling/camel-lsp-client-vscode/files/8085983/log_extension_host.log)

**Comment by apupier** [comment] 2022-02-17 10:54
it was a side-effect of upgrading to log4j 2 which had huge consequences only on MacOS
Fixed with https://github.com/camel-tooling/camel-language-server/pull/735

A new release with the fix is planned for March.
Current workaround is to use a snapshot version more recent than 0.2.0-1385 from https://download.jboss.org/jbosstools/vscode/snapshots/vscode-apache-camel/
After installing the vsix, restart the VS Code instance.

Bbig thanks to @tkamata-redhat for the great bug report and to @tkamata-redhat and @djelinek for investigation help.

**Closed by apupier** 2022-02-17 10:54 UTC
